import Head from 'next/head'
import DragFile2 from '../components/DragFile2'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cifrado AES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DragFile2/>
      <footer className={styles.footer}>
        <a
          href="https://github.com/DiegoPonzio/5IV7_SWyA_RPD"
          target="_blank"
          rel="noopener noreferrer"
        >
          Inserte CSS :(
        </a>
      </footer>
    </div>
  )
}