import Head from 'next/head'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cifrado AES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Bienvenido al Cifrador y Descifrador de AES, elige lo que quieras hacer: </h2>
      <br></br>
      <button><a href='./Cifrar'>Cifrar</a></button><br></br>
      <button><a href='./Descifrar'>Descifrar</a></button>
      <footer className={styles.footer}>
        <a
          href="https://github.com/DiegoPonzio/5IV7_SWyA_RPD"
          target="_blank"
          rel="noopener noreferrer"
        >
          Inserte CSS :(
        </a>
      </footer>
    </div>
  )
}
